"""PR summary skill: generates a review summary for pull requests."""

from __future__ import annotations

import importlib.resources
import time

from github_auto_maintainer.core.actions import PRReviewSummaryAction
from github_auto_maintainer.core.errors import SkillExecutionError, SkillResponseParsingError
from github_auto_maintainer.core.llm_types import LLMMessage
from github_auto_maintainer.core.task_types import TaskComplexity, TaskType
from github_auto_maintainer.github.diff_parser import parse_diff
from github_auto_maintainer.github.errors import GitHubClientError
from github_auto_maintainer.github.events import NormalizedEvent
from github_auto_maintainer.skills.base import BaseSkill, SkillContext, SkillResult
from github_auto_maintainer.skills.decisions import PRSummaryDecision, make_decision_validator
from github_auto_maintainer.skills.payload import (
    extract_pull_request_number,
    extract_repository_name,
    extract_repository_owner,
)

_HANDLED_EVENTS = frozenset({"pull_request.opened"})


def _load_prompt_template() -> str:
    files = importlib.resources.files("github_auto_maintainer.prompts")
    return files.joinpath("pr_summary.md").read_text(encoding="utf-8")


def _compute_routing(
    total_changed: int, total_files: int
) -> tuple[TaskType, TaskComplexity]:
    """Route by PR size: small→SUMMARIZATION/LOW, medium→SUMMARIZATION/MEDIUM, large→SUMMARIZATION/HIGH."""
    if total_changed < 50 and total_files <= 3:
        return TaskType.SUMMARIZATION, TaskComplexity.LOW
    if total_changed < 300 and total_files <= 10:
        return TaskType.SUMMARIZATION, TaskComplexity.MEDIUM
    return TaskType.SUMMARIZATION, TaskComplexity.HIGH


def _format_review_body(decision: PRSummaryDecision) -> str:
    """Build a markdown review body from the PR summary decision."""
    lines: list[str] = []
    lines.append("## Summary")
    lines.append("")
    lines.append(decision.summary)
    lines.append("")
    lines.append("## Key Changes")
    lines.append("")
    for change in decision.key_changes:
        lines.append(f"- {change}")
    lines.append("")
    if decision.suggestions:
        lines.append("## Suggestions")
        lines.append("")
        for suggestion in decision.suggestions:
            lines.append(f"- {suggestion}")
        lines.append("")
    lines.append(f"**Risk Level:** {decision.risk_level}")
    lines.append("")
    lines.append("---")
    lines.append("*Generated by GitHub Auto-Maintainer*")
    return "\n".join(lines)


class PRSummarySkill(BaseSkill):
    """Generate a review summary for incoming pull requests."""

    @property
    def name(self) -> str:
        return "pr_summary"

    @property
    def description(self) -> str:
        return "Generate a summary review for pull requests."

    @property
    def default_task_type(self) -> TaskType:
        return TaskType.SUMMARIZATION

    @property
    def default_complexity(self) -> TaskComplexity:
        return TaskComplexity.LOW

    def handles_event(self, event: NormalizedEvent) -> bool:
        return event.event_name in _HANDLED_EVENTS

    async def execute(self, context: SkillContext) -> SkillResult[PRSummaryDecision]:
        start = time.monotonic()
        event = context.event
        payload = event.payload

        owner = extract_repository_owner(payload)
        repo = extract_repository_name(payload)
        pr_number = extract_pull_request_number(payload)

        try:
            pr = await context.github_client.get_pull_request(owner, repo, pr_number)
            raw_diff = await context.github_client.get_pull_request_diff(owner, repo, pr_number)
        except GitHubClientError as exc:
            raise SkillExecutionError(
                f"Failed to fetch PR data for {owner}/{repo}#{pr_number}: {exc}"
            ) from exc

        file_diffs = parse_diff(raw_diff)
        total_additions = sum(f.additions for f in file_diffs)
        total_deletions = sum(f.deletions for f in file_diffs)
        total_files = len(file_diffs)
        total_changed = total_additions + total_deletions

        task_type, complexity = _compute_routing(total_changed, total_files)

        file_summary = "\n".join(
            f"  {fd.new_path or fd.old_path or '(unknown)'}: "
            f"+{fd.additions}/-{fd.deletions} ({fd.status})"
            for fd in file_diffs
        )

        template = _load_prompt_template()
        prompt = template.format(
            pr_number=pr.number,
            title=pr.title,
            author=pr.author,
            base_ref=pr.base_ref,
            head_ref=pr.head_ref,
            body=pr.body or "(no description)",
            total_files_changed=total_files,
            total_additions=total_additions,
            total_deletions=total_deletions,
            file_summary=file_summary or "(no files)",
            diff_content=raw_diff[:8000] if len(raw_diff) > 8000 else raw_diff,
        )

        validator = make_decision_validator(PRSummaryDecision)
        messages: list[LLMMessage] = [{"role": "user", "content": prompt}]

        response = await context.router.complete_with_escalation(
            "You are a code review assistant. Respond with raw JSON only.",
            messages,
            2048,
            0.2,
            task_type,
            complexity,
            validator,
        )

        try:
            decision = PRSummaryDecision.from_llm_response(response.content)
        except SkillResponseParsingError as exc:
            raise SkillExecutionError(
                f"Failed to parse PR summary decision after escalation: {exc}"
            ) from exc

        review_body = _format_review_body(decision)

        elapsed = time.monotonic() - start
        return SkillResult(
            skill_name=self.name,
            event_delivery_id=event.delivery_id,
            decision=decision,
            confidence=0.8 if validator(response) else 0.5,
            reasoning=decision.summary,
            recommended_actions=(
                f"post_review_summary:{owner}/{repo}#{pr_number}",
            ),
            model_used=response.model,
            task_type_used=task_type,
            complexity_used=complexity,
            elapsed_seconds=round(elapsed, 3),
            planned_actions=(
                PRReviewSummaryAction(
                    owner=owner,
                    repo=repo,
                    pr_number=pr_number,
                    body=review_body,
                ),
            ),
            escalation_count=response.escalation_count,
        )
